### POST a pais (para tener un id de país válido)
# @name createPais
POST http://localhost:3000/api/paises
Content-Type: application/json

{
    "nombrePais": "Argentina",
    "descripcionPais": "País de Sudamérica."
}

### paisId
@paisId = {{createPais.response.body.data.id}}

### GET all localidades
GET http://localhost:3000/api/localidades

### POST a localidad
# @name createLocalidad
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombreLocalidad": "Rosario",
    "descripcionLocalidad": "Ciudad de la provincia de Santa Fe.",
    "pais": {{paisId}}
}

### ID
@id = {{createLocalidad.response.body.data.id}}

### GET one localidad
GET http://localhost:3000/api/localidades/{{id}}

### PUT a localidad
PUT http://localhost:3000/api/localidades/{{id}}
Content-Type: application/json

{
    "nombreLocalidad": "Rosario",
    "descripcionLocalidad": "Ciudad de la provincia de Santa Fe, a orillas del río Paraná.",
    "pais": {{paisId}}
}

### POST a localidad to delete
# @name createLocalidadToDelete
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombreLocalidad": "LocalidadBorrar",
    "descripcionLocalidad": "Para borrar.",
    "pais": {{paisId}}
}

### DELETE a localidad
@idToDelete = {{createLocalidadToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/localidades/{{idToDelete}}

### PATCH a localidad
PATCH http://localhost:3000/api/localidades/{{id}}
Content-Type: application/json

{
    "descripcionLocalidad": "Descripción actualizada por PATCH."
}
